// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitle("Plainion.GraphViz.Modules.CodeInspection.Tests")]
[assembly: AssemblyProduct("Plainion.GraphViz")]
[assembly: AssemblyDescription("Plainion.GraphViz")]
[assembly: AssemblyCopyright("Copyright @ 2023")]
[assembly: AssemblyVersion("5.2")]
[assembly: AssemblyFileVersion("5.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.GraphViz.Modules.CodeInspection.Tests";
        internal const System.String AssemblyProduct = "Plainion.GraphViz";
        internal const System.String AssemblyDescription = "Plainion.GraphViz";
        internal const System.String AssemblyCopyright = "Copyright @ 2023";
        internal const System.String AssemblyVersion = "5.2";
        internal const System.String AssemblyFileVersion = "5.2";
    }
}
