// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Plainion.GraphViz")]
[assembly: AssemblyProductAttribute("Plainion.GraphViz")]
[assembly: AssemblyDescriptionAttribute("Plainion.GraphViz")]
[assembly: AssemblyCopyrightAttribute("Copyright @ 2017")]
[assembly: AssemblyVersionAttribute("2.5.0")]
[assembly: AssemblyFileVersionAttribute("2.5.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.GraphViz";
        internal const System.String AssemblyProduct = "Plainion.GraphViz";
        internal const System.String AssemblyDescription = "Plainion.GraphViz";
        internal const System.String AssemblyCopyright = "Copyright @ 2017";
        internal const System.String AssemblyVersion = "2.5.0";
        internal const System.String AssemblyFileVersion = "2.5.0";
    }
}
