// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitle("Plainion.GraphViz")]
[assembly: AssemblyProduct("Plainion.GraphViz")]
[assembly: AssemblyDescription("Plainion.GraphViz")]
[assembly: AssemblyCopyright("Copyright @ 2025")]
[assembly: AssemblyVersion("8.3")]
[assembly: AssemblyFileVersion("8.3")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.GraphViz";
        internal const System.String AssemblyProduct = "Plainion.GraphViz";
        internal const System.String AssemblyDescription = "Plainion.GraphViz";
        internal const System.String AssemblyCopyright = "Copyright @ 2025";
        internal const System.String AssemblyVersion = "8.3";
        internal const System.String AssemblyFileVersion = "8.3";
    }
}
