// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Plainion.GraphViz.Modules.Documents")]
[assembly: AssemblyProductAttribute("Plainion.GraphViz")]
[assembly: AssemblyDescriptionAttribute("Plainion.GraphViz")]
[assembly: AssemblyCopyrightAttribute("Copyright @ 2020")]
[assembly: AssemblyVersionAttribute("3.4")]
[assembly: AssemblyFileVersionAttribute("3.4")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.GraphViz.Modules.Documents";
        internal const System.String AssemblyProduct = "Plainion.GraphViz";
        internal const System.String AssemblyDescription = "Plainion.GraphViz";
        internal const System.String AssemblyCopyright = "Copyright @ 2020";
        internal const System.String AssemblyVersion = "3.4";
        internal const System.String AssemblyFileVersion = "3.4";
    }
}
