// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Plainion.GraphViz.Viewer")]
[assembly: AssemblyProductAttribute("Plainion.GraphViz")]
[assembly: AssemblyDescriptionAttribute("Plainion.GraphViz")]
[assembly: AssemblyCopyrightAttribute("Copyright @ 2017")]
[assembly: AssemblyVersionAttribute("1.21.0")]
[assembly: AssemblyFileVersionAttribute("1.21.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.GraphViz.Viewer";
        internal const System.String AssemblyProduct = "Plainion.GraphViz";
        internal const System.String AssemblyDescription = "Plainion.GraphViz";
        internal const System.String AssemblyCopyright = "Copyright @ 2017";
        internal const System.String AssemblyVersion = "1.21.0";
        internal const System.String AssemblyFileVersion = "1.21.0";
    }
}
