// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyTitle("Plainion.GraphViz.Modules.MdFiles")]
[assembly: AssemblyProduct("Plainion.GraphViz")]
[assembly: AssemblyDescription("Plainion.GraphViz")]
[assembly: AssemblyCopyright("Copyright @ 2023")]
[assembly: AssemblyVersion("5.0")]
[assembly: AssemblyFileVersion("5.0")]
[assembly: InternalsVisibleTo("Plainion.GraphViz.Modules.MdFiles.Tests")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.GraphViz.Modules.MdFiles";
        internal const System.String AssemblyProduct = "Plainion.GraphViz";
        internal const System.String AssemblyDescription = "Plainion.GraphViz";
        internal const System.String AssemblyCopyright = "Copyright @ 2023";
        internal const System.String AssemblyVersion = "5.0";
        internal const System.String AssemblyFileVersion = "5.0";
    }
}
