// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Plainion.GraphViz.Modules.CodeInspection")]
[assembly: AssemblyProductAttribute("Plainion.GraphViz")]
[assembly: AssemblyDescriptionAttribute("Plainion.GraphViz")]
[assembly: AssemblyCopyrightAttribute("Copyright @ 2019")]
[assembly: AssemblyVersionAttribute("3.1")]
[assembly: AssemblyFileVersionAttribute("3.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.GraphViz.Modules.CodeInspection";
        internal const System.String AssemblyProduct = "Plainion.GraphViz";
        internal const System.String AssemblyDescription = "Plainion.GraphViz";
        internal const System.String AssemblyCopyright = "Copyright @ 2019";
        internal const System.String AssemblyVersion = "3.1";
        internal const System.String AssemblyFileVersion = "3.1";
    }
}
