// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitle("Plainion.Graphs")]
[assembly: AssemblyProduct("Plainion.GraphVGraphsiz")]
[assembly: AssemblyDescription("Plainion.Graphs")]
[assembly: AssemblyCopyright("Copyright @ 2025")]
[assembly: AssemblyVersion("8.2")]
[assembly: AssemblyFileVersion("8.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.Graphs";
        internal const System.String AssemblyProduct = "Plainion.Graphs";
        internal const System.String AssemblyDescription = "Plainion.Graphs";
        internal const System.String AssemblyCopyright = "Copyright @ 2025";
        internal const System.String AssemblyVersion = "8.2";
        internal const System.String AssemblyFileVersion = "8.2";
    }
}
