// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Plainion.GraphViz.Help")>]
[<assembly: AssemblyProductAttribute("Plainion.GraphViz")>]
[<assembly: AssemblyDescriptionAttribute("Plainion.GraphViz")>]
[<assembly: AssemblyCopyrightAttribute("Copyright @ 2021")>]
[<assembly: AssemblyVersionAttribute("3.6")>]
[<assembly: AssemblyFileVersionAttribute("3.6")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Plainion.GraphViz.Help"
    let [<Literal>] AssemblyProduct = "Plainion.GraphViz"
    let [<Literal>] AssemblyDescription = "Plainion.GraphViz"
    let [<Literal>] AssemblyCopyright = "Copyright @ 2021"
    let [<Literal>] AssemblyVersion = "3.6"
    let [<Literal>] AssemblyFileVersion = "3.6"
