// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Plainion.GraphViz.Help")>]
[<assembly: AssemblyProductAttribute("Plainion.GraphViz")>]
[<assembly: AssemblyDescriptionAttribute("Plainion.GraphViz")>]
[<assembly: AssemblyCopyrightAttribute("Copyright @ 2019")>]
[<assembly: AssemblyVersionAttribute("2.12.0")>]
[<assembly: AssemblyFileVersionAttribute("2.12.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Plainion.GraphViz.Help"
    let [<Literal>] AssemblyProduct = "Plainion.GraphViz"
    let [<Literal>] AssemblyDescription = "Plainion.GraphViz"
    let [<Literal>] AssemblyCopyright = "Copyright @ 2019"
    let [<Literal>] AssemblyVersion = "2.12.0"
    let [<Literal>] AssemblyFileVersion = "2.12.0"
